### ISSUE TITLE
can't update or uninstall

### ISSUE THREAD

**Issue by monkeymoong** [Amourspirit/libreoffice_ooodev_ext#102]
hi
i installed it on LibreOffice portable 24.8.2.1
but i can't update it and i can't uninstall it
when i try to update
Erreur lors de l'installation de l'extension OOO Development Tools. Le message d'erreur est le suivant : file/folder does not exist
L'extension ne sera pas installée.

when i try to uninstall
Ajouter des extensions:
Le dossier D:\0001-Applications_portables\DOC0-App.Libre.Office\App\libreoffice\program\..\program\..\..\..\Data\settings\user\extensions\tmp\extensions\lu18956d056y.tmp_ n'existe pas.

**Comment by Amourspirit** [comment]
I have not yet tried and tested LibrePyythonista on Portable LibreOffice for windows.

You can try resettng LibreOffice Portable user folder, which would wipe all installed setting and installed extensions.
**Warning:** If you try this you are responsible for what happens.

Make sure LibreOffice is closed.
So I would try, making a backup of `registrymodifications.xcu` located in `...\Data\settings\user\`.
Then delete the `user` folder in `...\Data\settings\`.
Create a new folder `user` in `...\Data\settings\`.
Copy `registrymodifications.xcu`  back into `...\Data\settings\user\`.
Start LibreOffice Portable again and is should recreate any missing folders in the `user` folder.
Reinstall extensions.

These steps have worked for me in the past. No guarantees it work for you.

**Comment by monkeymoong** [comment]
just for info,
it seems that i found the error
i had a space in my installation path
i made a fresh install on C: without any space and it's ok now...
i can install and uninstall with no error messages
