### ISSUE TITLE
ImportError: No module named 'ooodev' (or 'ooodev.utils.lo.Lo' is unknown)

### ISSUE THREAD

**Issue by yardern** [Amourspirit/libreoffice_ooodev_ext#37]
Thank you for developing and sharing this extension.

I installed this extension v0.18.2 into my LibreOffice v7.4.7.2 under Debian 12 x64.
When I run:
_**from ooodev.utils.lo import Lo**_
I got:
_**No module named 'ooodev'**_

Am I missing something?

**Comment by Amourspirit** [comment]
Did you try restarting LibreOffice after install of extension?

**Comment by yardern** [comment]
Yes, after the installation, it requested to restart and I did. I saw it poped up a small window, saying "pip ...".
I executed "from ooodev.utils.lo import Lo" in a py file from VSCode (with .venv and oooenv, all under a folder at /home), and got that problem.
After I "pip uninstall ooo-dev-tools", it then worked.

Today I created a new VM (kubuntu), installed your extension and VSCode (without venv, without oooenv), it worked!
I will keep it this way, put my scripts under .config/libreoffice/4/user/Scripts/python/ (This seems is the only place if I want to execute scripts from Calc by pressing a button?)

Thanks!

**Comment by Amourspirit** [comment]
Happy you got it working. I am not clear on how you are using `OOO Dev Tools` ( extension or Pip installing Package).

You have it working that is the important thing.
Also check out [ImportError: Are you sure that uno has been imported? #495](https://github.com/Amourspirit/python_ooo_dev_tools/issues/495) to see if it is related.

**Comment by yardern** [comment]
Sorry for my confusing answer.
Let me try it again:

In vmware player under Windows 10, I have a fresh installation of Debian 12, LibreOffice 7.4.7.2, apso 1.3.3.2 & ooodev 0.29.0 extensions and VSCode+Python.
I did not setup python virtual environment because LibreOffice needs python scripts under a specific folder, and I don't know how to set venv up for both the IDE and LibreOffice.
When I run:
**_from ooodev.utils.lo import lo_**
I got:
**No module named 'ooodev'**

When I did the same thing under kubuntu, it worked.

**Comment by Amourspirit** [comment]
Then it would make sense that that you would be having issues.
If possible don't use a Virtual Machine. Use [Live LibreOffice Python](https://github.com/Amourspirit/live-libreoffice-python) that  I have created instead, see the [wiki](https://github.com/Amourspirit/live-libreoffice-python/wiki). It works as a Codespace (Dev Environment), basically a docker image supported with LibreOffice and the virtual environment already baked in.

You can run the `Live LibreOffice Python` in you web browser if you needed to from a GitHub Code space (requires a GitHub Account).
Other options are, you can make a copy of the template, see [Getting Started](https://github.com/Amourspirit/live-libreoffice-python/wiki/Getting-Started), also you can just clone the repo and run it locally on your computer. as a development environment (docker image in VS Code or PyCharm). See also in the wiki [Can I run this project outside of a container?](https://github.com/Amourspirit/live-libreoffice-python/wiki/FAQ#can-i-run-this-project-outside-of-a-container).

Other resources: [LibreOffice Pip & Virtual Environments](https://python-ooo-dev-tools.readthedocs.io/en/latest/guide/virtual_env/index.html)

**Comment by yardern** [comment]
Thank you for the answer! They are way above my head.

Today I compared the 2 VMs of mine, and found the working one (kubuntu) has **_python site-package "ooodev" and "oooenv"_** installed in addition to the **_libreoffice "ooodev" extension_**.

Could you please let me know which ones are needed? There are many answers from Google search, and I don't know which one to follow.

Thank you again!

**Comment by Amourspirit** [comment]
I just wrote a guide related to this: [Linux Linking Paths for Development](https://python-ooo-dev-tools.readthedocs.io/en/main/guide/virtual_env/linux_linking_paths.html).

Have a look and see if it helps.

**Comment by yardern** [comment]
I followed the guide, I can put my python scripts any where I like now.

Thank you so much for the excellent program and guide!
